### ISSUE TITLE
WGR covariate regularization

### ISSUE THREAD

**Issue by eric-czech** [projectglow/glow#266]
I noticed that the REGENIE [preprint](https://www.biorxiv.org/content/10.1101/2020.06.19.162354v2.full.pdf) mentions covariate orthogonalization (implicitly removing covariate regularization) while this implementation uses constant alpha values of 1 here: https://github.com/projectglow/glow/blob/f3edf5bb8fe9c2d2e1a374d4402032ba5ce08e29/python/glow/wgr/linear_model/functions.py#L152

Is there any reason that shouldn't be `np.zeros(n_cov)` instead of 1's?  I'm curious if choosing a different model was intentional here since it would otherwise seem to simplify a good bit of the code if you could just project the covariates out from the start.

**Comment by LelandBarnard** [comment]
Hi Eric, thanks for the continued interest and detailed comments.  We chose 1's here instead of 0's to guard against rank deficiencies.  It does also have the effect of applying some regularization to the covariates, however we expect the features and labels to always have variance ~ 1 so applying alpha = 1 to the covariates in practice is a quite mild shrinkage that has a negligible effect on the parameter estimates.  

As for why we explicitly include the covariates in the ridge regression models rather than just projecting them out as is done in regenie, the main reason is that in glowgr currently we never have an entire block of snps from the genotype matrix in RAM at a time, whereas in regenie all computations are done in RAM so there is an opportunity to residualize the covariates out of the genotype matrix as each block of snps before the ridge regression step.

**Comment by eric-czech** [comment]
> why we explicitly include the covariates in the ridge regression models rather than just projecting them out as is done in regenie

Sounds good, I suppose having to do it again at each stage negates a good bit of the simplicity added by not needing to handle the covariates separately anyhow.

Thanks for explanation @LelandBarnard!
