### ISSUE TITLE
Glow implementation using Scala

### ISSUE THREAD

**Issue by veeteehimself** [projectglow/glow#451]
The GLOW Documentation generally contains the demonstration of the GLOW functionality using python. The same holds for the talk conducted by Mr Amir Kermany and Mr Kiavash Kianfa, which was titled "Genomic Variant Data Ingest and Manipulation using Glow".
Pardon the ignorance, if any, on my part, but I wanted to know if there is a documentation listing the usage of GLOW through Scala.

Moreover, I also wanted to know if there is a particular programming language that the GLOW team might prefer when I make contributions to the project very shortly.

Thanks for reading and investing your time in helping me out!

**Comment by williambrandler** [comment]
Hi @veeteehimself yes that's right most of the docs are in Python, 

because most bioinformatics scientists or computational biologists know Python, but relatively few know Scala (mostly bioinformatics engineers). However, most of the codebase is in Scala

Thanks for your interest in contributing. What kind of contributions do you intend to make? That will help determine what language(s) are best
